//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : 化简类.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//




public class 化简类 {
    private Object 传入的表达式：mn;
    private Object 传入的命令：order;
    private Object 化简式合法性：isRight;
    public void 化简式化简后合并() {
    
    }
    
    public void 数值代入，计算化简() {
    
    }
    
    public void getmn() {
    
    }
    
    public void setmn() {
    
    }
    
    public void setOrder() {
    
    }
    
    public void getOrder() {
    
    }
    
    public void getIsRight() {
    
    }
    
    public void setIsRight() {
    
    }
}
