//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : 多项式类.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//




public class 多项式类 {
    private Object 传入的表达式：String mn;
    private Object 表达式是否正确：boolean isRight;
    public void 表达式合法性判断() {
    
    }
    
    public void 拆分出数字，将表达式整理() {
    
    }
    
    public void 将表达式整合() {
    
    }
    
    public void 将表达式的相同项进行合并() {
    
    }
    
    public void getmn() {
    
    }
    
    public void setmn() {
    
    }
    
    public void getisRight() {
    
    }
    
    public void setisRight() {
    
    }
}
