//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : 求导类.java
//  @ Date : 2016/12/1
//  @ Author : 
//
//




public class 求导类 {
    private Object 传入的命令：order;
    private Object 命令的合法性判断：isRight;
    public void 检查求导式是否合法() {
    
    }
    
    public void 对相应的求导式进行求导() {
    
    }
    
    public void 计算未知数个数() {
    
    }
    
    public void 表达式按空格拆分() {
    
    }
}
